In [3]:
import numpy as np

In [87]:
from numpy import linalg as LA
a = np.matrix([[1, 2, 3], [2, 7, 4]])
b = np.matrix([[1, -1], [0, 1]])
c = np.matrix([[5, -1], [9, 1], [6, 0]])
d = np.matrix([[3, -2, -1], [1, 2, 3]])

u = np.array([6, 2, -3, 5])
v = np.array([3, 5, -1, 4])
w = np.matrix([[1], [8], [0], [5]])
matrices = [a, b, c, d, w]
vectors = [u, v]

##dimensions
for item in matrices:
    print item.shape

##vector operations

print u+v
print u - v
print 6*u
print np.dot(u,v)
print LA.norm(u)

##matrix operations
try:
    print a + c
except:
    print "not defined"
print a - c.transpose()
print c.transpose() +3*d
print b*a
try:
    print b*a.transpose
except:
    print "not defined"


(2, 3)
(2, 2)
(3, 2)
(2, 3)
(4, 1)
[ 9  7 -4  9]
[ 3 -3 -2  1]
[ 36  12 -18  30]
51
8.60232526704
not defined
[[-4 -7 -3]
 [ 3  6  4]]
[[14  3  3]
 [ 2  7  9]]
[[-1 -5 -1]
 [ 2  7  4]]
not defined


In [37]:
u = np.asarray(u, dtype=float)

ValueError: invalid literal for float(): 6 2 -3 5

(2, 3)
(2, 2)
(3, 2)
(2, 3)
(4, 1)
